const KEY='orionState';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{tasks:[],mins:0};
const $=id=>document.getElementById(id);const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function safe(s){return String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function render(){const list=$('taskList');if(!list)return;list.innerHTML='';state.tasks.forEach((t,i)=>{const li=document.createElement('li');li.className=t.done?'done':'';li.innerHTML='<input type="checkbox" '+(t.done?'checked':'')+'><span>'+safe(t.text)+'</span> <button>Delete</button>';li.querySelector('input').onchange=()=>{t.done=!t.done;save();render()};li.querySelector('button').onclick=()=>{state.tasks.splice(i,1);save();render()};list.appendChild(li)});const done=state.tasks.filter(t=>t.done).length;$('done').textContent=done;$('mins').textContent=state.mins;$('habits').textContent=Math.min(3,Math.floor(state.mins/25));const pct=state.tasks.length?Math.round(done/state.tasks.length*100):0;$('progress').style.width=pct+'%';$('progressText').textContent=pct+'% mission progress'}
let sec=1500,id=null;function clock(){const m=String(Math.floor(sec/60)).padStart(2,'0'),s=String(sec%60).padStart(2,'0');$('timer').textContent=m+':'+s}$('start').onclick=()=>{if(id)return;$('timerLabel').textContent='RUNNING';id=setInterval(()=>{sec--;clock();if(sec<=0){clearInterval(id);id=null;state.mins+=25;save();render();sec=1500;clock();$('timerLabel').textContent='DONE';$('start').textContent='Start focus session'}},1000);$('start').textContent='Session running…'};$('reset').onclick=()=>{clearInterval(id);id=null;sec=1500;clock();$('timerLabel').textContent='READY';$('start').textContent='Start focus session'};
$('taskForm').onsubmit=e=>{e.preventDefault();const x=$('taskInput'),t=x.value.trim();if(t){state.tasks.push({text:t,done:false});x.value='';save();render()}};$('clear').onclick=()=>{state.tasks=state.tasks.filter(t=>!t.done);save();render()};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('show'));$(b.dataset.view).classList.add('show');$('title').textContent=b.textContent.replace(/^./,'')});document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('prompt').value=b.dataset.prompt;$('prompt').focus()});$('promptForm').onsubmit=e=>{e.preventDefault();const p=$('prompt').value.trim();if(!p)return;const row=document.createElement('p');row.innerHTML='<b>YOU</b><br>'+safe(p)+'<br><br><b>ORION</b><br>'+safe(reply(p));$('chat').appendChild(row);$('prompt').value='';$('chat').scrollTop=$('chat').scrollHeight};function reply(t){const x=t.toLowerCase();if(x.includes('plan'))return'Break the goal into three small milestones, ship the smallest useful version, then test and document it.';if(x.includes('explain'))return'Start with a simple definition, one example, and one tiny exercise.';return'Next actions: choose one task, run a focused work block, ship a meaningful change, and record the result.'}
const github={repo:'life-os-student-dashboard',stars:0,forks:0,issues:0,commits:9,health:'BUILDING',activity:['feat: add GitHub intelligence dashboard','docs: define ORION AI architecture and roadmap','feat: build ORION AI command center','test: add manual smoke checks'],momentum:'Strong recent build momentum with multiple feature and documentation commits.',next:'Add automated checks, then ship a tagged release when the core flow is stable.',release:'No formal releases yet.'};
function renderGitHub(){for(const [id,val] of [['ghRepo',github.repo],['ghStars',github.stars],['ghForks',github.forks],['ghIssues',github.issues],['ghCommits',github.commits],['ghHealth',github.health]])if($(id))$(id).textContent=val;$('ghActivity').innerHTML=github.activity.map((x,i)=>`<li><b>${String(i+1).padStart(2,'0')}</b><span>${safe(x)}</span></li>`).join('');$('ghMomentum').textContent=github.momentum;$('ghNext').textContent=github.next;$('ghRelease').textContent=github.release}
$('refreshGithub')?.addEventListener('click',()=>{renderGitHub();const b=$('refreshGithub');b.textContent='Snapshot refreshed';setTimeout(()=>b.textContent='Refresh snapshot',1200)});setInterval(()=>{$('clock').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});},1000);$('date')&&($('date').textContent=new Date().toLocaleDateString());clock();render();renderGitHub();